groups:
  - name: disk-alerts
    rules:
      - alert: HighDiskUsage
        expr: |
          (1 -node_filesystem_avail_bytes{mountpoint="/",fstype!="tmpfs"}/node_filesystem_size_bytes{mountpoint="/",fstype!="tmpfs" } ) > 0.46
        for: 5s
        labels:
          severity: critical
        annotations:
          description: "Disk usage above 46%"